version: "3.8"
services:
  fastapi:
    image: python:3.8
    container_name: fastapi
    depends_on: 
      - localstack
    env_file:
      - .env
    build: .
    command: /bin/start-reload.sh
    environment:
      - DYNAMODB_LOCAL_URL=http://localstack:4566
    ports:
      - 8000:80
    volumes:
      - ./:/app
      - /app/.venv/
    networks:
      - web-network

  localstack:
    image: localstack/localstack
    container_name: localstack_main
    ports:
      - 4566:4566
    environment:
      - SERVICES=dynamodb
      - DEFAULT_REGION=us-east-2
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TMPDIR}
    volumes:
      - "./localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - web-network
  
networks:
  web-network:
    driver: bridge