version: '3.0'
services:
  dynamodb-local:
    command: "-optimizeDbBeforeStartup -dbPath ./data -port 8000"
    image: "amazon/dynamodb-local"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - "./app/db/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal

