version: '3.8'
services:
  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -optimizeDbBeforeStartup -dbPath ./data -port 8080"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "8080:8080"
    volumes:
      - "./app/db/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
