version: '3.0'
services:
  dynamodb-local:
    image: "amazon/dynamodb-local"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
  fastapi:
    environment: 
      - DYNAMODB_URL=http://dynamodb-local:8000
      - RUNTIME_ENVIRONMENT=test
    build: .
    container_name: fastapi
    ports:
      - "8080:8080"
    depends_on: 
      - dynamodb-local
    command: pytest -v
